ci: skip docker deploy pipline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,9 +17,9 @@ jobs:
             matrix:
                 node-version: [24.x]
         steps:
-            - uses: actions/checkout@v5
+            - uses: actions/checkout@v7.0.1
             - name: Use Node.js ${{ matrix.node-version }}
-              uses: actions/setup-node@v5
+              uses: actions/setup-node@v7.0.0
               with:
                   node-version: ${{ matrix.node-version }}
             - name: Install package
@@ -28,13 +28,13 @@ jobs:
               run: npm run lint
             - name: Build
               run: npm run build -- --configuration production
-            # - name: Unit Test
-            #   run: yarn ng test --browsers=ChromeHeadless --watch=false --code-coverage
+            - name: Unit Test
+              run: npm run test:ci
     build-docker:
         runs-on: ubuntu-latest
         needs: [build]
         steps:
-            - uses: actions/checkout@master
+            - uses: actions/checkout@v7.0.1
             # Container build
             - name: Build docker
               id: build-docker
@@ -42,35 +42,35 @@ jobs:
                   docker build . -t ${{ env.REGISTRY_NAME }}/damingerdai/hoteler-web:${{ github.sha }} -f Dockerfile
             - name: Image digest for docker
               run: echo ${{ steps.build-docker.outputs.digest }}
-            - name: Save docker image to tar file
-              run: |
-                  docker save ${{ env.REGISTRY_NAME }}/damingerdai/hoteler-web:${{ github.sha }} -o hoteler-web.tar
-                  chmod 664 hoteler-web.tar
-            - name: copy file via ssh password
-              uses: appleboy/scp-action@v0.1.7
-              with:
-                  host: ${{ secrets.SERVER_HOST }}
-                  username: ${{ secrets.SERVER_USERNAME }}
-                  password: ${{ secrets.SERVER_PASSWORD }}
-                  source: hoteler-web.tar
-                  target: ${{ secrets.SERVER_TARGET_FOLDER_PATHs }}
-    deploy:
-        runs-on: ${{ matrix.os }}
-        needs: [build-docker]
-        strategy:
-            fail-fast: true
-            matrix:
-                os: [ubuntu-latest]
-        steps:
-            - name: deploy by ssh
-              uses: appleboy/ssh-action@v1.2.5
-              with:
-                  host: ${{ secrets.SERVER_HOST }}
-                  username: ${{ secrets.SERVER_USERNAME }}
-                  password: ${{ secrets.SERVER_PASSWORD }}
-                  script: |
-                      set -e
-                      cd /root/Workspace/hoteler &&
-                      docker load -i hoteler-web.tar &&
-                      kubectl set image deployment/hoteler-web hoteler-web=${{ env.REGISTRY_NAME }}/damingerdai/hoteler-web:${{ github.sha }} -n hoteler-namespace &&
-                      kubectl rollout status deployment/hoteler-web -n hoteler-namespace
+            # - name: Save docker image to tar file
+            #   run: |
+            #       docker save ${{ env.REGISTRY_NAME }}/damingerdai/hoteler-web:${{ github.sha }} -o hoteler-web.tar
+            #       chmod 664 hoteler-web.tar
+            # - name: copy file via ssh password
+            #   uses: appleboy/scp-action@v0.1.7
+            #   with:
+            #       host: ${{ secrets.SERVER_HOST }}
+            #       username: ${{ secrets.SERVER_USERNAME }}
+            #       password: ${{ secrets.SERVER_PASSWORD }}
+            #       source: hoteler-web.tar
+            #       target: ${{ secrets.SERVER_TARGET_FOLDER_PATHs }}
+    # deploy:
+    #     runs-on: ${{ matrix.os }}
+    #     needs: [build-docker]
+    #     strategy:
+    #         fail-fast: true
+    #         matrix:
+    #             os: [ubuntu-latest]
+    #     steps:
+    #         - name: deploy by ssh
+    #           uses: appleboy/ssh-action@v1.2.5
+    #           with:
+    #               host: ${{ secrets.SERVER_HOST }}
+    #               username: ${{ secrets.SERVER_USERNAME }}
+    #               password: ${{ secrets.SERVER_PASSWORD }}
+    #               script: |
+    #                   set -e
+    #                   cd /root/Workspace/hoteler &&
+    #                   docker load -i hoteler-web.tar &&
+    #                   kubectl set image deployment/hoteler-web hoteler-web=${{ env.REGISTRY_NAME }}/damingerdai/hoteler-web:${{ github.sha }} -n hoteler-namespace &&
+    #                   kubectl rollout status deployment/hoteler-web -n hoteler-namespace
